# Generated by Django 3.1 on 2020-08-10 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyName', models.CharField(max_length=100)),
                ('PropertyDescription', models.CharField(max_length=100)),
                ('PropertyState', models.CharField(max_length=20)),
                ('PropertyLocation', models.CharField(max_length=100)),
                ('Agent_Property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.agent')),
            ],
        ),
        migrations.CreateModel(
            name='SubProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubPropertyName', models.CharField(max_length=100)),
                ('SubPropertyDescription', models.CharField(max_length=100)),
                ('SubPropertyState', models.CharField(choices=[('VC', 'Vacant'), ('RT', 'Rented'), ('EX', 'Expired'), ('PP', 'Part Payment')], default='VC', max_length=100)),
                ('RentRate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('AmountPaidSofar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('AmountToBalance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('EffectiveDate', models.DateField(default=datetime.datetime(2020, 8, 10, 20, 35, 0, 734186, tzinfo=utc), verbose_name='When Property was given out')),
                ('ExpiryDate', models.DateField(default=datetime.datetime(2020, 8, 10, 20, 35, 0, 734223, tzinfo=utc), verbose_name='Rent Expiry Date')),
                ('PaymentState', models.CharField(default='YETTOPAY', max_length=20)),
                ('PresentOccupant', models.CharField(default='NONE', max_length=100)),
                ('PresentOccupantID', models.CharField(default='NONE', max_length=100)),
                ('CurrentRunningPeriod', models.CharField(default='SAMPLE :FROM  JAN 1900 TO JAN JAN1900', max_length=100)),
                ('Property_SubProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheManager.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PresentOccupant', models.CharField(max_length=100)),
                ('OccupantPhoneNo', models.CharField(max_length=100)),
                ('Referee', models.CharField(max_length=100, verbose_name='Referee Name')),
                ('OccupantRefDetails', models.CharField(max_length=100, verbose_name='Referee Information')),
                ('TenantPhoto', models.ImageField(upload_to='TenantPhotos')),
                ('TenantState', models.CharField(choices=[('PR', 'Present'), ('DW', 'Done')], default='PR', max_length=100)),
                ('CurrentRunningPeriod', models.CharField(max_length=50)),
                ('CurrentRentRate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('AmountPaidSofar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('AmountToBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('FirstEngagementDate', models.DateField(default=datetime.datetime(2020, 8, 10, 20, 35, 0, 735331, tzinfo=utc), verbose_name='Date Property was given out')),
                ('SubProperty_Tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.subproperty')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicRentTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartingPeriod', models.DateField(verbose_name='Date Property was given out')),
                ('EndingPeriod', models.DateField(verbose_name='Expiry Date of Rent')),
                ('CurrentRunningPeriod', models.CharField(max_length=50)),
                ('RentRate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('AmountPaidSofar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('AmountToBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Tenant_RentTransactions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmountPaid', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='How much do you want to pay ? ')),
                ('DateOfPayment', models.DateField(default=datetime.datetime(2020, 8, 10, 20, 35, 0, 737316, tzinfo=utc), verbose_name='Payment Date')),
                ('PeriodicRentTransactions_DetailTransactions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.periodicrenttransactions')),
            ],
        ),
    ]
