# Generated by Django 3.0.7 on 2020-07-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyName', models.CharField(max_length=100)),
                ('PropertyState', models.CharField(max_length=100)),
                ('PropertyLocation', models.CharField(max_length=100)),
                ('PropertyDescription', models.CharField(max_length=100)),
                ('Agent_Property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='SubProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubPropertyName', models.CharField(max_length=100)),
                ('SubPropertyDescription', models.CharField(max_length=100)),
                ('SubPropertyState', models.CharField(max_length=100)),
                ('RentRate', models.DecimalField(decimal_places=5, max_digits=9)),
                ('EffectiveDate', models.DateField(verbose_name='date Property was given out')),
                ('ExpiryDate', models.CharField(max_length=100)),
                ('PaymentState', models.CharField(max_length=100)),
                ('Property_SubProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheManager.Property')),
            ],
        ),
        migrations.CreateModel(
            name='RentTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartingPeriod', models.DateField(verbose_name='date Property was given out')),
                ('EndingPeriod', models.DateField(verbose_name='date Property was given out')),
                ('AmountPaid', models.DecimalField(decimal_places=5, max_digits=9)),
                ('AmountToBalance', models.DecimalField(decimal_places=5, max_digits=9)),
                ('PresentOccupant', models.CharField(max_length=100)),
                ('OccupantPhoneNo', models.CharField(max_length=100)),
                ('OccupantRefDetails', models.CharField(max_length=100)),
                ('Referee', models.CharField(max_length=100)),
                ('SubProperty_RentTransactions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.SubProperty')),
            ],
        ),
    ]
