# Generated by Django 3.1 on 2020-08-11 01:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyName', models.CharField(max_length=100)),
                ('PropertyDescription', models.CharField(max_length=100)),
                ('PropertyState', models.CharField(max_length=20)),
                ('PropertyLocation', models.CharField(max_length=100)),
                ('Agent_Property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.agent')),
            ],
        ),
        migrations.CreateModel(
            name='SubProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubPropertyName', models.CharField(max_length=100)),
                ('SubPropertyDescription', models.CharField(max_length=100)),
                ('SubPropertyState', models.CharField(choices=[('VACANT', 'VACANT'), ('RENTED', 'RENTED'), ('EXPIRED', 'EXPIRED'), ('YET TO BALANCE UP', 'YET TO BALANCE UP')], default='VACANT', max_length=100)),
                ('RentRate', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='RENT AMOUNT')),
                ('AmountPaidSofar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='TOTAL PAID SO FAR (Auto Fill)')),
                ('AmountToBalance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='BALANCE (Auto Fill)')),
                ('EffectiveDate', models.DateField(default=datetime.datetime(2020, 8, 11, 1, 10, 17, 139662, tzinfo=utc), verbose_name='WHEN THE PROPERTY WAS GIVEN OUT(Auto Fill)')),
                ('ExpiryDate', models.DateField(default=datetime.datetime(2020, 8, 11, 1, 10, 17, 139696, tzinfo=utc), verbose_name='RENT EXPIRY DATE(Auto Fill)')),
                ('PaymentState', models.CharField(default='YET TO BALANCE UP', max_length=20, verbose_name='PAYMENT STATE (Auto Fill)')),
                ('PresentOccupant', models.CharField(default='NONE', max_length=100, verbose_name='PRESENT OCCUPANT (Auto Fill)')),
                ('PresentOccupantID', models.CharField(default='NONE', max_length=100)),
                ('CurrentRunningPeriod', models.CharField(default='SAMPLE :FROM  JAN 1900 TO JAN JAN1900', max_length=100)),
                ('Property_SubProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheManager.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PresentOccupant', models.CharField(max_length=100, verbose_name='FULL NAME')),
                ('OccupantPhoneNo', models.CharField(max_length=100, verbose_name='PHONE NO')),
                ('Referee', models.CharField(max_length=100, verbose_name='REFEREE NAME')),
                ('OccupantRefDetails', models.CharField(max_length=100, verbose_name='REFEREE INFORMATION')),
                ('TenantPhoto', models.ImageField(upload_to='TenantPhotos', verbose_name='PASSPORT PHOTO')),
                ('TenantState', models.CharField(choices=[('PR', 'Present'), ('DW', 'Done')], default='PR', max_length=100)),
                ('CurrentRunningPeriod', models.CharField(max_length=50, verbose_name='PERIOD OF RENT')),
                ('CurrentRentRate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='TOTAL AMOUNT FOR PERIOD (Auto Fill)')),
                ('AmountPaidSofar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='AMOUNT PAID SO FAR (Auto Fill)')),
                ('AmountToBalance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BALANCE (Auto Fill)')),
                ('FirstEngagementDate', models.DateField(default=datetime.datetime(2020, 8, 11, 1, 10, 17, 140819, tzinfo=utc), verbose_name='DATE PROPERTY WAS FIRST GIVEN OUT')),
                ('PaymentState', models.CharField(default='YET TO BALANCE UP', max_length=20, verbose_name='BALANCE (Auto Fill)')),
                ('SubProperty_Tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.subproperty')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicRentTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartingPeriod', models.DateField(verbose_name='Date Property was given out')),
                ('EndingPeriod', models.DateField(verbose_name='Expiry Date of Rent')),
                ('CurrentRunningPeriod', models.CharField(max_length=50, verbose_name='PERIOD OF RENT')),
                ('RentRate', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='RENT RATE (Auto Fill)')),
                ('AmountPaidSofar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='AMOUNT PAID SO FAR (Auto Fill)')),
                ('AmountToBalance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='REMAINING BALANCE (Auto Fill)')),
                ('Tenant_RentTransactions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmountPaid', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='How much do you want to pay ? ')),
                ('DateOfPayment', models.DateField(default=datetime.datetime(2020, 8, 11, 1, 10, 17, 142964, tzinfo=utc), verbose_name='Payment Date')),
                ('PeriodicRentTransactions_DetailTransactions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TheManager.periodicrenttransactions')),
            ],
        ),
    ]
