# Generated by Django 3.0.7 on 2020-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='PropertyState',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='renttransactions',
            name='AmountPaid',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='renttransactions',
            name='AmountToBalance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='renttransactions',
            name='EndingPeriod',
            field=models.DateTimeField(verbose_name='Expiry Date of Rent'),
        ),
        migrations.AlterField(
            model_name='renttransactions',
            name='StartingPeriod',
            field=models.DateTimeField(verbose_name='Date Property was given out'),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='ExpiryDate',
            field=models.DateField(verbose_name='Rent Expiry Date'),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='PaymentState',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='RentRate',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='SubPropertyState',
            field=models.CharField(choices=[('VC', 'Vacant'), ('RT', 'Rented'), ('EX', 'Expired')], default='VC', max_length=100),
        ),
    ]
