# Generated by Django 3.1 on 2020-08-24 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TheManager', '0002_auto_20200811_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='TenantPhoto',
        ),
        migrations.AlterField(
            model_name='detailtransactions',
            name='DateOfPayment',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 23, 55, 49, 131133, tzinfo=utc), verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='EffectiveDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 23, 55, 49, 128213, tzinfo=utc), verbose_name='WHEN THE PROPERTY WAS GIVEN OUT(Auto Fill)'),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='ExpiryDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 23, 55, 49, 128252, tzinfo=utc), verbose_name='RENT EXPIRY DATE(Auto Fill)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='FirstEngagementDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 23, 55, 49, 129343, tzinfo=utc), verbose_name='DATE PROPERTY WAS FIRST GIVEN OUT'),
        ),
    ]
