# Generated by Django 3.0.8 on 2020-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheManager', '0002_auto_20200704_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproperty',
            name='EffectiveDate',
            field=models.DateTimeField(verbose_name='date Property was given out'),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='ExpiryDate',
            field=models.DateTimeField(verbose_name='Rent Expiry Date'),
        ),
    ]
