# Generated by Django 3.1 on 2020-08-25 00:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TheManager', '0003_auto_20200824_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='TenantPhoto',
            field=models.ImageField(blank=True, upload_to='TenantPhotos', verbose_name='PASSPORT PHOTO'),
        ),
        migrations.AlterField(
            model_name='detailtransactions',
            name='DateOfPayment',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 0, 8, 18, 76042, tzinfo=utc), verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='EffectiveDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 0, 8, 18, 72701, tzinfo=utc), verbose_name='WHEN THE PROPERTY WAS GIVEN OUT(Auto Fill)'),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='ExpiryDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 0, 8, 18, 72740, tzinfo=utc), verbose_name='RENT EXPIRY DATE(Auto Fill)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='AmountToBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='BALANCE (Auto Fill)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='CurrentRentRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='TOTAL AMOUNT FOR PERIOD (Auto Fill)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='FirstEngagementDate',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 0, 8, 18, 73864, tzinfo=utc), verbose_name='DATE PROPERTY WAS FIRST GIVEN OUT'),
        ),
    ]
